name       : cutter
version    : 1.10.0
release    : 5
homepage   : https://cutter.re/
source     :
    - https://github.com/radareorg/cutter/archive/v1.10.0.tar.gz : 3a121638e056a05059aa3792943af1696f4e035661d01c179e45cb9baf00245a
    - git|https://github.com/radareorg/r2ghidra-dec.git : b8904026f983acfd6b392ac6c3167478828b6b13
license    : GPL-3.0-or-later
component  : programming.tools
summary    : A Qt and C++ GUI for radare2 reverse engineering framework
description: |
    Cutter is a free and open-source GUI for radare2. Willing to create an advanced, customizable and free reverse engineering framework.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(libr)
    - pkgconfig(python3)
setup      : |
    %qmake src/Cutter.pro \
        CUTTER_ENABLE_PYTHON=true \
        CUTTER_R2GHIDRA_STATIC=true \
        PREFIX=/usr \
        R2GHIDRA_SOURCE=$sources/r2ghidra-dec.git
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    ln -s /usr/bin/Cutter $installdir/usr/bin/cutter
