name       : cutter
version    : 1.11.1
release    : 11
homepage   : https://cutter.re/
source     :
    - git|https://github.com/radareorg/cutter.git : v1.11.1
license    : GPL-3.0-or-later
component  : programming.tools
summary    : A Qt and C++ GUI for radare2 reverse engineering framework
description: |
    Cutter is a free and open-source GUI for radare2. Willing to create an advanced, customizable and free reverse engineering framework.
patterns   :
    - devel :
        - /usr/lib64/Cutter/*.cmake
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(libr)
    - pkgconfig(python3)
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja \
        -DCUTTER_ENABLE_PYTHON=ON \
        -S ../src
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 src/org.radare.Cutter.appdata.xml $installdir/usr/share/metainfo/org.radare.Cutter.appdata.xml
    ln -s /usr/bin/Cutter $installdir/usr/bin/cutter
