name       : cutter
version    : 2.2.0
release    : 25
homepage   : https://cutter.re/
source     :
    - https://github.com/rizinorg/cutter/releases/download/v2.2.0/Cutter-v2.2.0-src.tar.gz : f5d2017c657ffb0eb001710e111a05b3068b40a29b51f5d8f4a650a037329f35
license    : GPL-3.0-or-later
component  : programming.tools
summary    : A Qt and C++ GUI for rizin reverse engineering framework
description: |
    Cutter is a free and open-source GUI for rizin. Willing to create an advanced, customizable and free reverse engineering framework.
patterns   :
    - devel :
        - /usr/lib64/Cutter/*.cmake
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(libgvc)
    - pkgconfig(python3)
    - pkgconfig(rz_core)
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja \
        -DCUTTER_ENABLE_PYTHON=ON \
        -DCUTTER_USE_ADDITIONAL_RIZIN_PATHS=OFF \
        -DCUTTER_USE_BUNDLED_RIZIN=OFF \
        -DPYTHON_EXECUTABLE=/usr/bin/python3
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 src/re.rizin.cutter.appdata.xml $installdir/usr/share/metainfo/re.rizin.cutter.appdata.xml
