name       : cutter
version    : 2.1.2
release    : 24
homepage   : https://cutter.re/
source     :
    - https://github.com/rizinorg/cutter/releases/download/v2.1.2/Cutter-v2.1.2-src.tar.gz : 088351e280d158e07498098ffba355a6272c2e4faf4b350ac7778e369eb23fe1
license    : GPL-3.0-or-later
component  : programming.tools
summary    : A Qt and C++ GUI for rizin reverse engineering framework
description: |
    Cutter is a free and open-source GUI for rizin. Willing to create an advanced, customizable and free reverse engineering framework.
patterns   :
    - devel :
        - /usr/lib64/Cutter/*.cmake
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(libgvc)
    - pkgconfig(python3)
    - pkgconfig(rz_core)
    - syntax-highlighting-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Set-minimum-version-for-Python-interpreter.patch
    %cmake_ninja \
        -DCUTTER_ENABLE_PYTHON=ON \
        -DCUTTER_USE_ADDITIONAL_RIZIN_PATHS=OFF \
        -DCUTTER_USE_BUNDLED_RIZIN=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 src/re.rizin.cutter.appdata.xml $installdir/usr/share/metainfo/re.rizin.cutter.appdata.xml
