name       : cutter
version    : 1.8.3
release    : 1
homepage   : https://cutter.re/
source     :
    - https://github.com/radareorg/cutter/archive/v1.8.3.tar.gz : 71014ec5a00f1255978c8298a3e1a84fa968ac327188333b5ea684b515e61fda
license    : GPL-3.0-or-later
component  : programming.tools
summary    : A Qt and C++ GUI for radare2 reverse engineering framework
description: |
    Cutter is a free and open-source GUI for radare2. Willing to create an advanced, customizable and free reverse engineering framework.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(libr)
    - pkgconfig(python3)
setup      : |
    %qmake src/Cutter.pro CUTTER_ENABLE_PYTHON=true
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    ln -s /usr/bin/Cutter $installdir/usr/bin/cutter
